### ISSUE TITLE
can't parse @apply

### ISSUE THREAD

**Issue by LuKks** [adobe/css-tools#35]
It seems that `@apply` can't be parsed properly? reworkcss/css also has this problem and I tried with an open PR that they have but I couldn't make it work.

```
[Error]: :176:3: missing '}'
    at h (/self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:2043)
    at j (/self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:3488)
    at M (/self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:5918)
    at d (/self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:2283)
    at /self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:5979
    at Object.e.parse (/self/project/node_modules/@adobe/css-tools/dist/umd/cssTools.js:1:6086) {
  reason: "missing '}'",
  filename: '',
  line: 176,
  column: 3,
  source: '@apply font-bold py-2 px-4 rounded;\n' +
    '}\n' +
```

```css
.div {
  @apply font-bold py-2 px-4 rounded;
}
```

It's not priority as I can remove the `@apply` but it would be cool to support it?

**Comment by holblin** [comment]
It clearly would be nice to support more use-cases :-)

It seems that @apply was a proposal and was since abandoned. Though it could be interesting to handle it differently.

I will see what I could do but it might take time. I'm going on vacation soon until the end of September.

**Comment by LuKks** [comment]
Hey, no worries!

It's also something related to `tailwind`:
https://tailwindcss.com/docs/functions-and-directives#apply

I removed `@apply` from the css files (which it was almost no used) and it's all good now. Have happy vacations :)

Feel free to close!
